name: release
run-name: 'Release'
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/build.yml
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-extension-package
          path: '*.vsix'
          if-no-files-found: error

  create-release:
    runs-on: ubuntu-22.04
    env:
      RELEASE_MANAGEMENT_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_RELEASE_MANAGEMENT }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: vscode-extension-package
      - run: |
          RELEASE_VERSION=$(jq --raw-output '.version' package.json)
          curl "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases" \
            -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${RELEASE_MANAGEMENT_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{ \"tag_name\": \"$RELEASE_VERSION}\", "target_commitish": "", \"name\": \"$RELEASE_VERSION}\" }"
